name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Check for merge conflicts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --base main --head dev --state open --json number --jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            echo "No open PR from dev to main. Exiting."
            exit 0
          fi

          echo "Found PR #$PR_NUMBER"

          # Check for merge conflicts
          gh pr view $PR_NUMBER --json mergeable --jq '.mergeable' | grep "MERGEABLE"

          if [ $? -eq 0 ]; then
            echo "PR is mergeable. Merging now..."
            gh pr merge $PR_NUMBER --squash --delete-branch
          else
            echo "PR has conflicts. Manual review needed."
            exit 1
          fi
