name: rs-quant

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Install sqlx-cli
        run: cargo install sqlx-cli

      - name: Cache SQLx Prepared Data # ✅ Cache entire `.sqlx/` directory
        uses: actions/cache@v3
        with:
          path: .sqlx/ # ✅ Cache the entire .sqlx directory
          key: ${{ runner.os }}-sqlx-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-sqlx-

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Get latest commit message
        id: commit
        run: echo "MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Create Pull Request
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head dev --title "$MESSAGE" --body "$MESSAGE" --label "passing"
